// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_k70u4VRFdJqBRzKT52QqDXv35l1Mnw4',
    appId: '1:56621047578:android:baefa4e3e6345b01f616a3',
    messagingSenderId: '56621047578',
    projectId: 'mmetfone-13ab5',
    databaseURL: 'https://mmetfone-13ab5.firebaseio.com',
    storageBucket: 'mmetfone-13ab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8CEwmuFyCgRbZEJjNNaLJ0CyTPhZN9wk',
    appId: '1:56621047578:ios:5045c975bad6b333f616a3',
    messagingSenderId: '56621047578',
    projectId: 'mmetfone-13ab5',
    databaseURL: 'https://mmetfone-13ab5.firebaseio.com',
    storageBucket: 'mmetfone-13ab5.firebasestorage.app',
    androidClientId:
        '56621047578-0icinf88ge9s3jn7sos5ul57u9p7sghb.apps.googleusercontent.com',
    iosClientId:
        '56621047578-tok5p995ijmn3nd9acelud8lrbipu5o9.apps.googleusercontent.com',
    iosBundleId: 'com.vtg.app.mymetfone.dev',
  );
}
